spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/jay/blog/dao/*.xml



comment.avatar: /images/avatar.png

logging:
  path: ./logs
  level:
    com:
      jay:
        blog: INFO

---
# redis configuration
spring:
  redis:
    database: 0
    host: 120.78.158.142
    port: 6379
    password: xieJIE!!...

  rabbitmq:
    username: root
    password: xieJIE123...
    host: 120.78.158.142

es:
 port: 9200
 hostname: 42.192.92.114

